In [1]:
import pandas as pd
import numpy as np

/Users/crystalbravo/opt/anaconda3/lib/python3.9/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/Users/crystalbravo/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


### Create Datasource

In [2]:
n = 26
idx = np.arange(n)

### Shuffle indexs

In [4]:
np.random.shuffle(idx)

In [5]:
idx


array([22,  0, 12,  2, 17, 25, 21,  4, 11,  3,  6, 16,  5, 24, 18,  7, 14,
       10,  8, 19, 15, 20,  1,  9, 13, 23])

### Get first nth elements

In [19]:
nth = 5

In [7]:
test = idx[:nth]
test

array([22,  0, 12,  2, 17])

### int to char

In [8]:
test = test + ord('a')
test

array([119,  97, 109,  99, 114])

In [18]:
test_ch = list(map(lambda n: chr(n), test))
test_ch

['w', 'a', 'm', 'c', 'r']

In [22]:
sourceFile = "Accupunture_Points.csv"

In [30]:
dataframe1 = pd.read_csv(sourceFile,header=None)

In [31]:
dataframe1.head()

0      1   2
0  LU01  LU-01  中府
1  LU02  LU-02  雲門
2  LU03  LU-03  天府
3  LU04  LU-04  俠白
4  LU05  LU-05  尺澤

In [47]:
dataframe = dataframe1[[1,2]]
dataframe = dataframe.rename(columns={1: "no", 2: "name"})
dataframe.head()

no name
0  LU-01   中府
1  LU-02   雲門
2  LU-03   天府
3  LU-04   俠白
4  LU-05   尺澤

### dataframe to dictionary

In [48]:
df= dataframe.to_dict('records')
df

[{'no': 'LU-01', 'name': '中府'},
 {'no': 'LU-02', 'name': '雲門'},
 {'no': 'LU-03', 'name': '天府'},
 {'no': 'LU-04', 'name': '俠白'},
 {'no': 'LU-05', 'name': '尺澤'},
 {'no': 'LU-06', 'name': '孔最'},
 {'no': 'LU-07', 'name': '列缺'},
 {'no': 'LU-08', 'name': '經渠'},
 {'no': 'LU-09', 'name': '太淵'},
 {'no': 'LU-10', 'name': '魚際'},
 {'no': 'LU-11', 'name': '少商'},
 {'no': 'LI-01', 'name': '商陽'},
 {'no': 'LI-02', 'name': '二間'},
 {'no': 'LI-03', 'name': '三間'},
 {'no': 'LI-04', 'name': '合谷'},
 {'no': 'LI-05', 'name': '陽谿'},
 {'no': 'LI-06', 'name': '偏歷'},
 {'no': 'LI-07', 'name': '溫溜'},
 {'no': 'LI-08', 'name': '下臁'},
 {'no': 'LI-09', 'name': '上臁'},
 {'no': 'LI-10', 'name': '手三里'},
 {'no': 'LI-11', 'name': '曲池'},
 {'no': 'LI-12', 'name': '肘髎'},
 {'no': 'LI-13', 'name': '手五里'},
 {'no': 'LI-14', 'name': '臂臑'},
 {'no': 'LI-15', 'name': '肩骨禺'},
 {'no': 'LI-16', 'name': '巨骨'},
 {'no': 'LI-17', 'name': '天鼎'},
 {'no': 'LI-18', 'name': '扶突'},
 {'no': 'LI-19', 'name': '禾髎'},
 {'no': 'LI-20', 'name': '迎香'},
 {'no

In [54]:
n = len(df)
idx = np.arange(n)

### Show testing items

In [57]:
np.random.shuffle(idx)
tests = idx[:nth]
for i in tests:
    print(df[i]["no"])

ST-43
SP-02
ST-06
LI-15
ST-27


### Show testing item names

In [56]:
for i in tests:
    print(df[i]["name"])

府舍
天谿
衝陽
梁丘
迎香
